version: '3.9'
services:
  nextjs:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/weborg?schema=public
    depends_on:
      - postgres
  postgres:
    image: postgres:14.6-alpine3.16
    command: -c log_destination=stderr -c log_statement=all
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      TZ: JST-9
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=ja_JP.UTF-8 --lc-ctype=ja_JP.UTF-8 --lc-messages=ja_JP.UTF-8'
      POSTGRES_DB: 'weborg'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - "5432:5432"
    restart: "no"

volumes:
  postgres-data:
