import './globals.css'
import type { Metadata } from 'next'
import { NextAuthProvider } from './sessionProvider'
import Sidebar from './components/sidebar.component'

export const metadata: Metadata = {
  title: 'WebOrg',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Sidebar />
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  )
}
